import { computeIndicators, roundToTick } from "./indicators";
import { providerById, type Timeframe } from "./coins";
import {
  fetchConsistentMarketData,
  fetchFearAndGreed,
  fetchGlobalCryptoMetrics,
} from "./market.server";
import type { SignalRequest, SignalResult } from "./signal-types";
import { parseJsonLoose, runChat, validateAiExplanation } from "./ai-providers.server";
import { SignalEngine } from "./engine/SignalEngine";

const SYSTEM_PROMPT = `You are a professional crypto technical analyst. You are given a calculated trade setup generated by a deterministic trading engine.
Your ONLY job is to write:
1. A concise, professional natural-language "summary" explaining the confluence reasons, entry trigger type, and directional bias.
2. A clear "invalidation" description explaining the exact structural conditions that would prove this setup wrong.
Do NOT invent or alter prices/levels: keep the output strictly aligned with the engine data provided.
Respond with ONLY a JSON object:
{"summary":"polished professional explanation","invalidation":"what would prove this setup wrong"}`;

export async function generateSignal(req: SignalRequest): Promise<SignalResult> {
  const symbol = req.symbol.toUpperCase().trim();
  const tf = req.timeframe;

  // Determine required timeframes dynamically based on requested timeframe
  const requestedTfs: Timeframe[] =
    tf === "1d" || tf === "1w"
      ? ["1w", "1d", "4h", "1h", "15m"]
      : tf === "4h" || tf === "8h"
        ? ["1d", "4h", "1h", "15m", "5m"]
        : tf === "1h"
          ? ["1d", "4h", "1h", "15m", "5m"]
          : ["4h", "1h", "15m", "5m"];

  // 1. Fetch multi-timeframe candles and ticker consistently from ONE single exchange
  const [marketData, sentiment, globalMetrics] = await Promise.all([
    fetchConsistentMarketData(symbol, requestedTfs),
    fetchFearAndGreed(),
    fetchGlobalCryptoMetrics(),
  ]);

  const candles1w = marketData.candles["1w"] || marketData.candles["1d"] || [];
  const candles1d = marketData.candles["1d"] || [];
  const candles4h = marketData.candles["4h"] || [];
  const candles1h = marketData.candles["1h"] || [];
  const candles15m = marketData.candles["15m"] || [];
  const candles5m = marketData.candles["5m"] || candles15m;

  // Cascade selection
  let macroCandles = candles1d;
  let regimeCandles = candles4h;
  let structCandles = candles1h;
  let setupCandles = candles15m;
  let triggerCandles = candles5m;

  if (tf === "1d" || tf === "1w") {
    macroCandles = candles1w.length ? candles1w : candles1d;
    regimeCandles = candles1d;
    structCandles = candles4h;
    setupCandles = candles1h;
    triggerCandles = candles15m;
  } else if (tf === "5m") {
    macroCandles = candles4h;
    regimeCandles = candles1h;
    structCandles = candles15m;
    setupCandles = candles5m;
    triggerCandles = candles5m;
  }

  const ticker = marketData.ticker;
  const price =
    ticker.price ||
    triggerCandles[triggerCandles.length - 1]?.close ||
    setupCandles[setupCandles.length - 1]?.close ||
    0;

  const provider = providerById(req.provider);
  const model = req.model?.trim() || provider.defaultModel;

  // 2. Run deterministic SignalEngine
  const signal = SignalEngine.run(
    symbol,
    macroCandles,
    regimeCandles,
    structCandles,
    setupCandles,
    triggerCandles,
    price,
    req.config,
    tf,
  );

  // 3. AI comes LAST: generate natural-language explanation only
  const btcDomText = globalMetrics ? `${globalMetrics.btcDominance}%` : "N/A";
  const userPrompt = JSON.stringify({
    symbol,
    direction: signal.direction,
    confluenceScore: signal.confluenceScore,
    confidence: signal.confidence,
    directionalEdge: signal.directionalEdge,
    entryType: signal.entryType,
    triggerCondition: signal.triggerCondition,
    entry: signal.entry,
    stopLoss: signal.stopLoss,
    target1: signal.takeProfit.tp1,
    target2: signal.takeProfit.tp2,
    target3: signal.takeProfit.tp3,
    marketRegime: signal.marketRegime,
    reasons: signal.reasons,
    rejectionReasons: signal.rejectionReasons,
    fearAndGreedIndex: sentiment ? `${sentiment.value} (${sentiment.sentiment})` : "N/A",
    btcDominance: btcDomText,
    timeframe: req.timeframe,
  });

  // Deterministic fallbacks
  let aiSummary =
    signal.direction === "NO TRADE"
      ? `No high-probability active trade setup identified for ${symbol} on the ${tf.toUpperCase()} horizon. ${signal.rejectionReasons[0] || "Market is in directional equilibrium."} Capital preservation is prioritized.`
      : `Deterministic ${signal.direction} setup identified with Confluence ${signal.confluenceScore}/100 (${signal.confidence} confidence, +${signal.directionalEdge} pts edge). Entry model: ${signal.entryType} (${signal.triggerCondition}). Risk managed at $${signal.stopLoss.toLocaleString()} targeting $${signal.takeProfit.tp1.toLocaleString()} (TP1) and $${signal.takeProfit.tp2.toLocaleString()} (TP2).`;

  let aiInvalidation = signal.invalidation;

  try {
    const raw = await runChat({
      provider: req.provider,
      model,
      apiKey: req.apiKey,
      system: SYSTEM_PROMPT,
      user: userPrompt,
    });
    const parsed = parseJsonLoose(raw);
    const validated = validateAiExplanation(parsed);
    if (validated) {
      aiSummary = validated.summary;
      aiInvalidation = validated.invalidation;
    }
  } catch (e) {
    console.warn("[signal] AI generation fallback to deterministic explanation:", e);
  }

  // Format reasoning array for client view
  const reasoning = signal.reasons.map((r) => {
    const parts = r.split(": ");
    return {
      label: parts[0] || "Evidence",
      detail: parts[1] || r,
    };
  });

  if (globalMetrics) {
    reasoning.push({
      label: "BTC Dominance",
      detail: `BTC.D is at ${globalMetrics.btcDominance}%. ${
        symbol === "BTC"
          ? "BTC leads systemic market capital flows."
          : "Altcoins require sustained BTC stability for breakout follow-through."
      }`,
    });
  }

  // Primary timeframe indicators for chart & display
  const primaryCandles =
    marketData.candles[tf] ||
    (tf === "1d"
      ? candles1d
      : tf === "4h"
        ? candles4h
        : tf === "1h"
          ? candles1h
          : tf === "15m"
            ? candles15m
            : candles5m);

  const primaryInd = computeIndicators(primaryCandles);

  return {
    symbol,
    timeframe: req.timeframe,
    generatedAt: new Date().toISOString(),
    modelUsed: `${provider.label} · ${model}`,
    dataSource: {
      exchange: marketData.source,
      candles: marketData.source,
      ticker: marketData.source,
      attempts: marketData.attempts,
    },
    currentPrice: price,
    change24hPct: ticker.change24hPct,
    high24h: ticker.high24h,
    low24h: ticker.low24h,
    marketRegime: signal.marketRegime,
    sentiment: sentiment ? { value: sentiment.value, label: sentiment.sentiment } : null,
    direction: signal.direction,
    confluenceScore: signal.confluenceScore,
    confidence: signal.confidence,
    directionalEdge: signal.directionalEdge,
    longScore: signal.longScore,
    shortScore: signal.shortScore,
    entryType: signal.entryType,
    entryZone: signal.entryZone,
    triggerCondition: signal.triggerCondition,
    expirationCandles: signal.expirationCandles,
    entry: roundToTick(signal.entry, price),
    stopLoss: roundToTick(signal.stopLoss, price),
    target1: roundToTick(signal.takeProfit.tp1, price),
    target2: roundToTick(signal.takeProfit.tp2, price),
    target3: signal.takeProfit.tp3 ? roundToTick(signal.takeProfit.tp3, price) : undefined,
    riskReward: signal.riskReward.tp2,
    summary: aiSummary,
    reasoning,
    rejectionReasons: signal.rejectionReasons,
    rejectionHierarchy: signal.rejectionHierarchy,
    invalidation: aiInvalidation,
    setupType: signal.setupType,
    indicators: {
      rsi: Number(primaryInd.rsi.toFixed(1)),
      macd: primaryInd.macd.macd,
      macdSignal: primaryInd.macd.signal,
      macdHistogram: primaryInd.macd.histogram,
      ema20: roundToTick(primaryInd.ema20, price),
      ema50: roundToTick(primaryInd.ema50, price),
      ema200: roundToTick(primaryInd.ema200, price),
      atr: roundToTick(primaryInd.atr, price),
      atrPct: Number(primaryInd.atrPct.toFixed(2)),
      swingHigh: roundToTick(primaryInd.swingHigh, price),
      swingLow: roundToTick(primaryInd.swingLow, price),
      trend: primaryInd.trend,
      volumeLabel: primaryInd.volume.label,
      volumeRatio: Number(primaryInd.volume.ratio.toFixed(2)),
    },
    candles: primaryCandles.slice(-80),
    // Legacy aliases
    setupScore: signal.confluenceScore,
    entryScore: signal.confluenceScore,
    finalScore: signal.confluenceScore,
  };
}

export async function generatePatternAnalysis(symbol: string, timeframe: string) {
  const { fetchCandles } = await import("./market.server");
  const { detectPatterns } = await import("./patterns");
  const res = await fetchCandles(symbol, timeframe as Timeframe);
  const candles = res.value;
  const patterns = detectPatterns(candles);
  return { candles, patterns };
}
