import { computeIndicators, roundToTick } from "./indicators";
import { providerById, TIMEFRAMES } from "./coins";
import { fetchCandles, fetchTicker, fetchFearAndGreed, fetchGlobalCryptoMetrics } from "./market.server";
import type { SignalRequest, SignalResult } from "./signal-types";
import { parseJsonLoose, runChat } from "./ai-providers.server";
import { SignalEngine } from "./engine/SignalEngine";
import { DEFAULT_CONFIG } from "./engine/config";

const SYSTEM_PROMPT = `You are a professional crypto technical analyst. You are given a calculated trade setup generated by a deterministic trading engine.
Your ONLY job is to write:
1. A concise, professional natural-language "summary" explaining the confluence reasons.
2. A clear "invalidation" description of what would prove the trade wrong.
Do NOT invent levels: keep the output strictly aligned with the data given.
Respond with ONLY a JSON object:
{"summary":"polished explanation","invalidation":"what would prove this setup wrong"}`;

export async function generateSignal(req: SignalRequest): Promise<SignalResult> {
  const symbol = req.symbol;
  
  // 1. Fetch candles for all 5 timeframes in parallel to enable multi-timeframe analysis
  const [candles1dRes, candles4hRes, candles1hRes, candles15mRes, candles5mRes, tickerRes, sentiment, globalMetrics] = await Promise.all([
    fetchCandles(symbol, "1d"),
    fetchCandles(symbol, "4h"),
    fetchCandles(symbol, "1h"),
    fetchCandles(symbol, "15m"),
    fetchCandles(symbol, "5m"),
    fetchTicker(symbol),
    fetchFearAndGreed(),
    fetchGlobalCryptoMetrics(),
  ]);

  const candles1d = candles1dRes.value;
  const candles4h = candles4hRes.value;
  const candles1h = candles1hRes.value;
  const candles15m = candles15mRes.value;
  const candles5m = candles5mRes.value;
  
  const ticker = tickerRes.value;
  const price = ticker.price || candles5m[candles5m.length - 1]?.close || 0;
  
  const provider = providerById(req.provider);
  const model = req.model?.trim() || provider.defaultModel;

  // Merge client config overrides if present
  const config = {
    ...DEFAULT_CONFIG,
    ...(req.config || {})
  };

  // 2. Run the deterministic SignalEngine
  const signal = SignalEngine.run(
    symbol,
    candles1d,
    candles4h,
    candles1h,
    candles15m,
    candles5m,
    price,
    config
  );

  // 3. Keep AI Separate From the Core Trading Logic
  // Call AI only for natural-language explanation/summarization
  const btcDomText = globalMetrics ? `${globalMetrics.btcDominance}%` : "N/A";
  const userPrompt = JSON.stringify({
    symbol,
    direction: signal.direction,
    entry: signal.entry,
    stopLoss: signal.stopLoss,
    target1: signal.takeProfit.tp1,
    target2: signal.takeProfit.tp2,
    target3: signal.takeProfit.tp3,
    marketRegime: signal.marketRegime,
    reasons: signal.reasons,
    rejectionReasons: signal.rejectionReasons,
    fearAndGreedIndex: sentiment ? `${sentiment.value} (${sentiment.sentiment})` : "N/A",
    btcDominance: btcDomText,
    timeframe: req.timeframe,
  });

  let aiSummary = "Analysis generated from live market data.";
  let aiInvalidation = signal.invalidation;

  try {
    const raw = await runChat({
      provider: req.provider,
      model,
      apiKey: req.apiKey,
      system: SYSTEM_PROMPT,
      user: userPrompt,
    });
    const parsed = parseJsonLoose(raw);
    if (parsed["summary"]) aiSummary = String(parsed["summary"]).slice(0, 600);
    if (parsed["invalidation"]) aiInvalidation = String(parsed["invalidation"]).slice(0, 400);
  } catch (e) {
    console.error("[signal] AI generation failed, using deterministic fallbacks:", e);
  }

  // Format reasoning array for client view
  const reasoning = signal.reasons.map((r) => {
    const parts = r.split(": ");
    return {
      label: parts[0] || "Note",
      detail: parts[1] || r,
    };
  });

  // Add macro metrics if available
  if (globalMetrics) {
    reasoning.push({
      label: "BTC Dominance",
      detail: `BTC.D is at ${globalMetrics.btcDominance}%. ${
        symbol === "BTC"
          ? "BTC is leading the capital flow index."
          : "Altcoins are heavily dependent on BTC.D trends for breakout extensions."
      }`,
    });
  }

  // Recalculate indicators for the primary timeframe (to return to client for main chart/stats)
  // Standardize back to the primary timeframe indicators
  const primaryCandles = req.timeframe === "1d" ? candles1d : req.timeframe === "4h" ? candles4h : req.timeframe === "1h" ? candles1h : req.timeframe === "15m" ? candles15m : candles5m;
  const primaryInd = computeIndicators(primaryCandles);

  return {
    symbol,
    timeframe: req.timeframe,
    generatedAt: new Date().toISOString(),
    modelUsed: `${provider.label} · ${model}`,
    dataSource: {
      candles: candles15mRes.source,
      ticker: tickerRes.source,
      attempts: [
        ...candles15mRes.attempts,
        ...tickerRes.attempts,
      ],
    },
    currentPrice: price,
    change24hPct: ticker.change24hPct,
    high24h: ticker.high24h,
    low24h: ticker.low24h,
    marketRegime: signal.marketRegime,
    sentiment: sentiment ? { value: sentiment.value, label: sentiment.sentiment } : null,
    direction: signal.direction,
    confidence: signal.finalScore,
    entry: roundToTick(signal.entry, price),
    stopLoss: roundToTick(signal.stopLoss, price),
    target1: roundToTick(signal.takeProfit.tp1, price),
    target2: roundToTick(signal.takeProfit.tp2, price),
    target3: roundToTick(signal.takeProfit.tp3, price),
    setupScore: signal.setupScore,
    entryScore: signal.entryScore,
    finalScore: signal.finalScore,
    rejectionReasons: signal.rejectionReasons,
    riskReward: signal.riskReward.tp2,
    summary: aiSummary,
    reasoning,
    invalidation: aiInvalidation,
    indicators: {
      rsi: Number(primaryInd.rsi.toFixed(1)),
      macd: primaryInd.macd.macd,
      macdSignal: primaryInd.macd.signal,
      macdHistogram: primaryInd.macd.histogram,
      ema20: roundToTick(primaryInd.ema20, price),
      ema50: roundToTick(primaryInd.ema50, price),
      ema200: roundToTick(primaryInd.ema200, price),
      atr: roundToTick(primaryInd.atr, price),
      atrPct: Number(primaryInd.atrPct.toFixed(2)),
      swingHigh: roundToTick(primaryInd.swingHigh, price),
      swingLow: roundToTick(primaryInd.swingLow, price),
      trend: primaryInd.trend,
      volumeLabel: primaryInd.volume.label,
      volumeRatio: Number(primaryInd.volume.ratio.toFixed(2)),
    },
    candles: primaryCandles.slice(-80),
  };
}

export async function generatePatternAnalysis(symbol: string, timeframe: string) {
  const { fetchCandles } = await import("./market.server");
  const { detectPatterns } = await import("./patterns");
  const res = await fetchCandles(symbol, timeframe as any);
  const candles = res.value;
  const patterns = detectPatterns(candles);
  return { candles, patterns };
}
